### ISSUE TITLE
2024 APAC Hosts Proposal Q&A: Questions for the ID Team

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#10]
We have received [ID's proposal](https://github.com/PyConAPAC/proposals/blob/master/2024/submissions/proposal-pycon-apac-2024-id.pdf) to host PyCon APAC 2024.

I'm opening up an Issue to keep Q&As public and available. If any member of the community has questions on needs clarification on the proposal, you can ask them on this Issue thread.

**Comment by sammyfung** [comment]
Thanks for ID team submitting the proposal!

1. About Transportation: May the local team tell us the cost of taxi or Uber (or similar services) for 3km distance (as you mentioned hotels in 3km distance from venue) ?

2. How much does the conference ticket cost ?

3. What's your expected size of the conference (how many participants do you expect) in 2024 ?

**Comment by Cheukting** [comment]
I already got the message that the place where the team propose is tourist-friendly, so there will be no problem checking in a double room with my unmarried partner, right?

I do not know many local team members, but I think it will be a good idea to have female (or anyone who is not self-identified as male) organisers in the team. As a woman myself, empowering women is an important point for me.

**Comment by dmaharika** [comment]
Hi @sammyfung , I'll be happy to answer the question.
1. We have two types of online taxis, one is using motorbikes (to transport only one person) and another one is using car. As for the cost, the first 5km of online motorbike taxis is usually about Rp15,000 or about 1 USD while the car is around Rp25,000 or about 2 USD.
2. PyCon ID 2023 general ticket cost is RP300,000 or about 20 USD. As for APAC 2024, the price may be higher a little but we will try to keep it under 50 USD. As that price is considered expensive for Indonesian participant.
3. We expect the conference attendance to be minimum of 500 persons.

**Comment by dmaharika** [comment]
Hi @Cheukting , as for your question. Here's our answer:
1. It's not gonna be a problem. Hotel staff usually won't bother to ask for your marriage certificate, especially if you are a tourist. You will be free to have a room together with who you want.
2. We do have some female organizer, especially in Yogyakarta region. Of course they will also participate in organizing this event.

**Comment by Cheukting** [comment]
Sorry, I have 1 more question, would there be any PyLadies activities at the conference?

**Comment by id-network** [comment]
@Cheukting Yes, we're planning for PyLadies inauguration event. Each city that has Python community always has female members and organizers, but usually not big enough to organize their own events. So we hope we can ignite stronger community involvement with this event.

**Comment by iqbalabd** [comment]
With the voting done, I am closing this issue.
