### ISSUE TITLE
2024 APAC Hosts Proposal Q&A: Questions for the KR Team

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#12]
We have received a [proposal to host PyCon APAC 2024 from the KR team](https://github.com/PyConAPAC/proposals/blob/master/2024/submissions/proposal-pycon-apac-2024-kr.pdf). I'm opening this issue to allow interested community members to ask questions or concerns concerning the proposal.

**Comment by ojii** [comment]
This years PyCon Korea seems to be entirely in Korean (based off the website). What are the plans for a potential PyCon APAC in Korea regarding language? Will the event be entirely in one language or multiple languages? What is the plan regarding the language of communication (before and during the event) of information?

**Comment by kst6294** [comment]
@ojii 
Thank you for your question. Please see below.

This year, we had tried to organize English session(by providing English CFP and notice information via Social Network),  but unfortunately it did not work. We carefully guess it might be due to flight issue and COVID-19.

We plan to provide English sessions, website, and relevant materials such as Pamphlet, Information book etc. (please check the English website of PyCon APAC 2016 hosted by PyCon KR Team: [https://archive.pycon.kr/2016apac]
(https://archive.pycon.kr/2016apac/)).

Before, during and after the PyCon APAC 2024, absolutely all working process (Notice, Email, CFP, sponsor, etc) will be provided in English as we

**Comment by sammyfung** [comment]
Thanks for KR team submitting the proposal!

It's a solid proposal to me, and show your team's experience in running APAC conferences.

I got 1 question.

What do you expect from running an APAC conference instead of running a local conference ? And what are good impacts to Korea and APAC community ?

**Comment by cpprhtn** [comment]
@sammyfung 

Thank you for the good question!

Korea is a region known for its concentration of technology, transportation, safety, and innovative technology companies. Hosting the APAC conference in Korea allows us to provide participants with a more innovative and cutting-edge experience. Additionally, Korea serves as a significant hub for international flight routes within the Asia-Pacific region, making it easily accessible for international participants. By leveraging these geographical advantages, hosting the APAC conference in Korea enables us to offer participants a better conference experience through technological innovation, cultural diversity, accessibility, and regional community development. Moreover, Korea's safe and stable security environment ensures participants' peace of mind and a comfortable experience.

The growing adoption of Python in Korea is strengthening the domestic Python community and promoting a more vibrant ecosystem. This trend isn't unique to Korea but is also seen in other APAC countries. Hosting a global Python conference in Korea allows for close observation and understanding of these evolving language preferences and their impact on the Korean market. This helps the Python community stay well-informed and prepared for potential applications and adaptations.

Additionally, hosting the APAC conference in Korea encourages Korean participants to engage in PyCon APAC events in other regions, fostering cross-cultural unity and facilitating knowledge exchange and networking within the broader APAC Python community.

**Comment by Cheukting** [comment]
I like Korean food but I know it is not friendly to everyone, maybe we can compose a list of vegetarian/ vegan food and non spicy food for the attendees?

I do not know many local team members, but I think it will be a good idea to have female (or anyone who is not self identified as male) organisers in the team. As a woman myself, empower women is an important point for me.

**Comment by darjeeling** [comment]
@Cheukting 

## about local team members

next year's PyCon KR team members didn't gathered yet. but by previous 10 years experience, team member 35~55% is not looks like male. 


## about food selection

actually we don't provide foods. but we have food selections near venue. so vegetarian and vegan food is not a problem.
also halal food provided near the venue.

But there is no standard on the spicy level. we'll take a look, it's much different by person. anyway there exist none spicy food with soy source, we can make recommendations.

**Comment by iqbalabd** [comment]
Just an observation and not a question: Different to much of our other PyCons, PyCon KR's organizing style has always been "without food" (as far as I can remember) so that's another different way of having conferences. It's of course another valid way to do our conferences and reduce the burden of the organizing community, and as an attendee, you get to mingle around with people by joining "looking for something to eat" squadrons at lunchtime.

**Comment by kst6294** [comment]
@iqbalabd 

I agree.
We will consider your advice. Thank you.

**Comment by Cheukting** [comment]
Sorry, I have 1 more question, would there be any PyLadies activities at the conference?

**Comment by kst6294** [comment]
@Cheukting 

Activities and details are not fixed yet, PyLadies activities either unfortunately. We are considering PyLadies' activities and we are trying to ask one of PyLadies member to be a keynote speaker as you can see on the CFP(Potential Keynote Proposal).
if you have any suggestion for the PyLadies Activities, please let us know! 
Thank you!

**Comment by kst6294** [comment]
@Cheukting 

We have no plan for the PyLadies activities yet. Thanks.

**Comment by iqbalabd** [comment]
With the voting done, I am closing this issue.
