### ISSUE TITLE
Will PH have enough time to prepare?

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#16]
The current proposed dates for PyCon APAC 2025 by PH is on Mar 1 to Mar 2. This is only around 4 months after the announcement of the hosts for 2025, compared to a lead time of around 11 months for the other proposals. Will PH have time to prepare?

Perhaps answering questions like:

- Have the venue been finalized and signed?
- How far the team is prepared in terms of organization (i.e. is the program team in place, keynote speakers fixed, ready to accept CfPs)

would help us understand how prepared the team is and OK with the short lead time.

**Comment by cr8ivecodesmith** [comment]
**Venue**

Venue has been pencil booked by Ateneo de Manila already. We just need to have them sign a Memorandum of Agreement.

**Preparations Timeline**

We officially kicked off preparations last September 25. This means each committee is now working on their task assignments already. This is also around the same time that we prepare every year.

PyCon PH 2024 was also a test run where we adopt a mindset of making it APAC quality whether its APAC or not.

**CFP**

CFP is scheduled to be posted this October.

**Comment by ismailsunni** [comment]
@cr8ivecodesmith if PH is not selected, what will happen with the preparations you already did? Perhaps keep the effor for PyCon PH 2025, right?

Based on PyCon PH 2024 report, it seems you guys are already know the field :+1:

**Comment by cr8ivecodesmith** [comment]
> @cr8ivecodesmith if PH is not selected, what will happen with the preparations you already did? Perhaps keep the effor for PyCon PH 2025, right?
> 
> Based on PyCon PH 2024 report, it seems you guys are already know the field 👍

Yes, that's correct. We intend to deliver as if its APAC.

**Comment by iqbalabd** [comment]
Closing this issue as we've already voted for the hosts
