### ISSUE TITLE
FOR ALL 2025 PROPOSALS: Estimated ticket prices

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#17]
None of the proposals have an estimate of the pricing of the ticket for attendees. Ticket prices are an important factor, so it would be great if we can get a ballpark figure in USD for this.

**Comment by codemickeycode** [comment]
For the **Philippines**, these are the estimated ticket prices at the **regular rate**:

|               | in PHP | in USD |
|---------------|--------|--------|
| Corporate     | 6,300  | 112    |
| Individual    | 3,600  | 64     |
| Student       | 1,800  | 32     |

We will also offer **early bird** and **late bird rates**.

**Comment by palnabarun** [comment]
PyCon India ticket pricing are as follows:

| Ticket Type | Price (INR) | Price (USD) |
| ----------- | ----------- | ----------- |
| Student     | 1500        | 18          |
| Early Bird  | 1500        | 18          |
| Regular     | 2000        | 24          |
| Late Bird   | 3000        | 36          |
| Contributor | 5000        | 60          |

On all the ticket tiers, a government tax gets applied as 18% of the ticket price.

Our ticket prices have remained almost same over the years. We plan to increase the prices by 10% next year to catch up with inflation.

We also have a scholarship program for students, speakers and attendees in-need who have been providing impact and/or have potential future impact to the Python Community.

**Comment by MadRex2000** [comment]
PyCon Taiwan Ticket Prices:
| Ticket Type | NTD| USD |
| :--- | :---: | :---: |
| Individual (Early) | 2,790| 87 |
| Individual (Regular) | 3,790 | 118 |
| Corporate| 5,800 | 181 |
| Contributor| 1,290 | 40 |

We expect total ticket sales to be approximately $34,000 USD.
Below is the estimated number of tickets sold:
| Ticket Type | Estimated Numbers |
| :--- | :---: |
| Individual (Early) | 105 |
| Individual (Regular) | 105 |
| Corporate| 50 |
| Contributor| 100 |

For corporate tickets, we also offer group discounts for companies purchasing multiple tickets.
We also offer financial aid for students or anyone in need, allowing them to apply for ticket discounts, including full-price discounts if necessary.

**Comment by iqbalabd** [comment]
Closing this issue as we've already voted for the hosts
