### ISSUE TITLE
FOR ALL 2025 PROPOSALS: Visa Free Travel?

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#18]
I would like to know how many countries within our East and South East Asian friends will have visa free travel to your countries? I know it's beyond the control of our community but it helps frame how much time we need to prepare.

To simplify things, I will define the our E/SE Asian countries as those actively involved within our group:

1. NP
2. CN
3. JP
4. KR
5. TW
6. PH
7. TH
8. MY
9. SG
10. ID
11. IN
12. AU
13. NZ

Can I request that the proposers make a table that shows which countries within the above require/does not require visa to attend the conference?

**Comment by MadRex2000** [comment]
The following are the countries in East and Southeast Asia whose citizens can travel to Taiwan visa free:
|     | Visa Free? | Note                                                        |
|:---:|:----------:|:----------------------------------------------------------- |
| NP  |     ❌     |                                                             |
| CN  |     ❌     |                                                             |
| JP  |     ✅     | visa free for 90 days                                       |
| KR  |     ✅     | visa free for 90 days                                       |
| PH  |     ❌     | visa free for 14 days now, but effective till July 31, 2025 |
| TH  |     ❌     | visa free for 14 days now, but effective till July 31, 2025 |
| MY  |     ✅     | visa free for 30 days                                       |
| SG  |     ✅     | visa free for 30 days                                       |
| ID  |     ❌     |                                                             |
| IN  |     ❌     |                                                             |
| AU  |     ✅     | visa free for 90 days                                       |
| NZ  |     ✅     | visa free for 90 days                                       |

In our proposal, we plan to hold PyCon APAC 2025 in September. Therefore, friends from the Philippines and Thailand will need to apply for a visa to attend.

**Comment by cr8ivecodesmith** [comment]
| Country       | Visa Free   | Notes                                                                                                                                                           |
|---------------|-------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nepal         | Yes         | 30 days visa-free                                                                                                                                               |
| China         | Conditional | Visa required; visa-free for 7 days if holding a valid visa from Australia, Japan, Canada, Schengen countries, or the US                                         |
| Japan         | Yes         | 30 days visa-free                                                                                                                                               |
| South Korea   | Yes         | 30 days visa-free                                                                                                                                               |
| Taiwan        | Conditional | Visa-free for 30 days with MECO Electronic Travel Authorization (ETA)                                                                                            |
| Philippines   | Yes         | N/A (Philippine citizens)                                                                                                                                        |
| Thailand      | Yes         | 30 days visa-free                                                                                                                                               |
| Malaysia      | Yes         | 30 days visa-free                                                                                                                                               |
| Singapore     | Yes         | 30 days visa-free                                                                                                                                               |
| Indonesia     | Yes         | 30 days visa-free                                                                                                                                               |
| India         | Conditional | Visa required; visa-free for 14 days if holding a valid visa or permanent residence permit from Japan, Australia, Canada, Schengen countries, Singapore, UK, or US |
| Australia     | Yes         | 30 days visa-free                                                                                                                                               |
| New Zealand   | Yes         | 30 days visa-free                                                                                                                                               |
| Hong Kong     | Yes         | 14 days visa-free for Hong Kong SAR passport holders; 7 days visa-free for holders of Hong Kong British passports                                                |

**Notes:**

- **China:** Chinese nationals require a visa but may enter visa-free for up to 7 days if they have a valid visa from Australia, Japan, Canada, Schengen countries, or the US.
- **Taiwan:** Taiwanese citizens can enter visa-free for 30 days if they possess a MECO Electronic Travel Authorization (ETA).
- **India:** Indian nationals require a visa but may enter visa-free for 14 days if they have a valid visa or permanent residence permit from Japan, Australia, Canada, Schengen countries, Singapore, the UK, or the US.
- **Hong Kong:**
  - **Hong Kong SAR passport holders:** Visa-free entry for 14 days.
  - **Holders of Hong Kong British passports:** Visa-free entry for 7 days, provided they have a return or onward ticket.

**Additional Clarifications:**

- **China:** The 7-day visa-free entry for Chinese nationals can be extended by an additional 14 days to a maximum of 21 days.
- **India:** The 14-day visa-free entry may be extended by an additional 7 days for a maximum of 21 days.
- **Taiwan:** MECO ETA holders are allowed an initial stay of 30 days.

**Comment by iqbalabd** [comment]
Closing this issue as we've already voted for the hosts
