### ISSUE TITLE
MY: Do you have ballpark dates for the satellite events and sprints?  

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#2]
Page 5 in MY's proposal: I was wondering if you can give ballpark dates for the satellite events. Can't you fit sprints during APAC too?

**Comment by ivyfung1** [comment]
Tentatively:
20th Sept: Embedded System showcase (application of Micropython)
20th Sept: Tutorial Workshop (Data science related topics)
17th Sept: Pre-event Dinner/Social Dinner. 
17th Sept: APAC communities Dialogue session.
17th Sept: Open Space (Informal Discussion/Demonstration on Python related topics)
16th & 17th Sept: Development Sprint (Documentation on interested projects)
16th Sept: Education Summit

**Comment by iqbalabd** [comment]
Understood @ivyfung1
