### ISSUE TITLE
TH: Why TH for the hosts

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#3]
You've written in the proposal on why Bangkok will be a great host, but can you also touch on _why_ TH should host APAC in 2021? Something that TH can bring to the table for the wider community for example.

**Comment by georgically** [comment]
1. Thailand has never hosted any PyCon APAC as of yet despite having many active Python-related communities. Some examples of the communities are mentioned on our proposal on page 9. Hosting the event could help gain more traction about PyCon to the Pythonistas based here.

2. PyCon APAC is still fairly new to the Pythonistas in Thailand and it's neighboring countries like Vietnam, Cambodia, Myanmar and Laos, where tech-related industries are thriving. Transportation is not only well connected by air, land and sea but also affordable. It's strategic location thus added as an advantage to be more accessible to both the local and foreign developers living in neighboring countries. 
We hope by hosting this event, we could inspire and encourage more participation from the Python Communities in the respective regions, thus enforcing a more pertinent PyCon APAC in the future.

**Comment by iqbalabd** [comment]
Understood @georgically .
