### ISSUE TITLE
100% online option

### ISSUE THREAD

**Issue by iqbalabd** [PyConAPAC/proposals#4]
Will both hosts be prepared for a 100% online hosting of PyCon APAC 2021 if in the case travel restrictions are still in place?

**Comment by georgically** [comment]
The PyConTH's  proposal has 2 plans. Virtual and Hybrid. 

Page 12 of the proposal depicts 2 different paths: Virtual (green on the left) and Hybrid (Blue on the right) 
TH team will decide (and of course through discussions with APAC members) on which path to choose 6 months prior to event date (mid-May 2021). Should travel restrictions remained as of current situation, we will adopt virtual path = 100% online.   

The rest of the proposal from page 13 onwards explains in details on how PyConTH will run the event with under two possible paths for each section. 
Example of a screenshot with sub-headers boxed in red: 
![example](https://user-images.githubusercontent.com/40323509/98396463-53e79f00-2090-11eb-9d55-bbc1e320f120.png)

**Comment by ivyfung1** [comment]
In case of travel restriction still in place, we will hold the event 100% online. 
With the experience from previous PyCon, we have in place a plan for automating tasks and improvement in content. 
Decision shall be made by April 2021. 
If the event is to be brought online 100%, the satellite events are planned to be held 3 months ahead of the main event.

**Comment by iqbalabd** [comment]
Thanks @georgically and @ivyfung1 . I will close this issue.
