### ISSUE TITLE
proposal to add todo of  PyCon APAC Host 

### ISSUE THREAD

**Issue by darjeeling** [PyConAPAC/proposals#8]
I'd like to talk about an additional proposal for what we'd like to ask the host country of PyCon APAC to do.

- If you are selected as the PyCon APAC Host, you will need to go through the process of selecting the next year's PyCon APAC Host.
- This should be done two months before the host's PyCon APAC schedule.
- It should be announced at the host's PyCon APAC Closing.

Adding the above to the PyCon APAC Host process will reduce the burden of running PyCon APAC and help maintain it.
We would appreciate your feedback.

**Comment by iqbalabd** [comment]
I basically agree with this proposal. It will be a self-sustaining mechanism which will remove the need to have a central person who coordinates the annual PyCon APAC, or at the very least reduces the load for this person.

Having said that, in order for a particular group to select the next host, that group needs a person who also knows the other members of the community, to communicate well and also send out suggestions. So we'll basically need some sort of a regional liaison person for each PyCon APAC year in each of the host's team. This means we'll need to move towards stronger ties between the difference communities.

We've never officially had it before, but I also suggest an official PyCon APAC summit during each PyCon APAC where the host will also require the next host to be present and also other members to discuss about stuff related to the conference.

**Comment by yungyuc** [comment]
Asking the current APAC host (community and the chairperson) to get involved in the selection of the next APAC host sounds like a good idea to me.  In my personal experience it greatly helps the stability and consistency of the community.  When it comes to the regional PyCon APAC, the consistency may be a very plausible outcome.
